version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ferc-story-postgres-dev
    environment:
      POSTGRES_DB: ferc_story
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - ferc-story-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ferc_story"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data_dev:

networks:
  ferc-story-network:
    driver: bridge
